build:
    environment:
        php: '7.2'
    tests:
        override:
            - [php-scrutinizer-run]
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - Tests/*
        - Examples/*
        - Documentation/*