language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - nightly

matrix:
  allow_failures:
      - php: nightly
      - php: '7.4snapshot'

install:
  - composer update

script:
  - vendor/bin/phpunit --coverage-clover build/coverage/xml

after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml